### ISSUE TITLE
Matrix -> Discord markdown headers aren't parsed correctly

### ISSUE THREAD

**Issue by anoadragon453** [matrix-discord/matrix-discord-parser#3]
I *believe* this belongs in this repo.

Sending a message with the content `# HELLO` from Matrix will result in:

![image](https://user-images.githubusercontent.com/1342360/73127438-2f667e80-3fb8-11ea-8ba9-ffb860376ae9.png)

but on discord will result in:

![image](https://user-images.githubusercontent.com/1342360/73127442-3f7e5e00-3fb8-11ea-9a4c-dfbe70ec0491.png)

I don't think Discord can do header text, so ideally it would just be bolded with no `#`, like so:

![image](https://user-images.githubusercontent.com/1342360/73127452-54f38800-3fb8-11ea-8882-33f04884139e.png)

**Comment by Sorunome** [comment]
How should further sub-headers be differentiated then, though?

**Comment by anoadragon453** [comment]
Hmm, that is a good point.

Perhaps it should be:

# HELLO
↓
**HELLO**

## HELLO
↓
**## HELLO**

etc

**Comment by Sorunome** [comment]
also casting to all uppercase on h1 and h2 or something?

**Comment by anoadragon453** [comment]
That could work

**Comment by Sorunome** [comment]
Fixed in https://github.com/matrix-discord/matrix-discord-parser/commit/29b282106a1245dd321da372eed7fc2821c06b1d
