### ISSUE TITLE
DiscordMessageParserResult wrong initilization

### ISSUE THREAD

**Issue by dylhack** [matrix-discord/matrix-discord-parser#4]
With [DiscordMessageParserResult](https://github.com/matrix-discord/matrix-discord-parser/blob/e6ab145fde5734251841a6e36e50ecdcd63ea8a2/src/discordmessageparser.ts#L55) having no constructor it could be a type or interface. This is a TypeScript compiler error TS2564.

**Comment by Sorunome** [comment]
hmmm unfortunately our linting requires interfaces to be prefixed with `I` and, well, that would break compability with programs. Not sure what the best approach is here :/

**Comment by dylhack** [comment]
I gone through and re-factored the usage of DiscordMessageParserResult as well as removing unused imports, variables, and a couple cleanups. See the following [fork](https://github.com/dhghf/matrix-discord-parser), it has yet to be tested.

**Comment by dylhack** [comment]
I've done it at [this commit](https://github.com/dhghf/matrix-discord-parser/commit/8c4f76fc37eed38eb342685dfe9cfd811b899c93)

**Comment by Sorunome** [comment]
If you want to contribute, please make a PR :)

Also, it is always a good idea to discuss refactoring things with the maintainers beforehand, a lot of changes in your branch aren't changes soru'd want to see here, unfortunately.

**Comment by dylhack** [comment]
All the refactors bind by the TSLint rules and all changes were minimal I double checked all the function signatures to make sure nothing was broken.

**Comment by dylhack** [comment]
Also maybe provide a Matrix room for discussions.

**Comment by Sorunome** [comment]
#discord:half-shot.uk

**Comment by Sorunome** [comment]
Fixed in https://github.com/matrix-discord/matrix-discord-parser/pull/5
